coverage:
  status:
    project:
      default: false # disable the default status that measures entire project
      tests:
        paths:
          - "tests/"
        target: 0%
      source:
        paths:
          - "finitediffx/"
        target: 0%
    patch:
      default:
        target: 0%
